= Main
:toc: right
:imagesdir: framework/images

Handle application lifecycle events via main.js.

== main.js
Enonic apps may contain a special "main.js" file. Place the file in `src/main/resources/main.js`.

`main.js` is invoked when an application lifecycle event occurs. A common use of is initialization like creating repositories, and registration of event listeners when the application starts, as well as cleaning up resources when the application stops.

The code should complete as quickly as possible to prevent application stalling. Never call remote endpoints or wait in loops for events inside the `main.js` global scope.

TIP: If you need to perform time consuming work in the main controller, consider implementing it as a <<tasks#, task>>.

Running code when the application starts:

.main.js
[source,javascript]
----
// Log application start
log.info('Application ' + app.name + ' started');
----

Running code when the application stops:

.main.js
[source,javascript]
----
// Log application stop
__.disposer(function() {
    log.info('Application ' + app.name + ' stopped');
});

----
