= Building Sites
:toc: right
:imagesdir: media

Use Enonic XP to deliver websites natively, without introducing a 3rd party front-end framework.

== Introduction

As an alternative to using 3rd party front-end frameworks like Next.js, you may use Enonic XP and Enonic Apps natively to deploy Content Schemas, and deliver advanced websites.


NOTE: TUTORIALS HERE!

== Usage

Unlike <<webapps#, XP webapps>>, XP sites do not have a default implementation — they resolve a component implementation based on the content being requested.

To implement a site, start by placing the site descriptors under `src/main/resources/cms/` of your project. The site descriptor is split into two files: `cms/site.yaml` (processors, mappings, and API mounts) and `cms/cms.yaml` (site form and mixin references).

Implement at least TODO: Add descriptor example and explain the main elements of it.


== Multiple apps per site
Sites may be powered by multiple apps. The apps may even collaborate on processing and responding to a single request. Similar to webapps, developers can use filters and mappings to take control over URL patterns when needed.

