= Admin library
:toc: right
:imagesdir: images

This API provides admin-related functions.

== Usage

Add the following to your `build.gradle` file:

[source,groovy]
----
dependencies {
  include xplibs.admin
}
----

Add the `import` statement to your code:

[source,typescript]
----
import adminLib from '/lib/xp/admin';
----

You are now ready to use the API.


== Functions

=== getInstallation

Returns the installation name.

[.lead]
Parameters

None

[.lead]
Returns

*string* : The installation name.

[.lead]
Example

[source,typescript]
----
import {getInstallation} from '/lib/xp/admin';

const name = getInstallation();
----

=== getVersion

Returns the version of the XP installation.

[.lead]
Parameters

None

[.lead]
Returns

*string* : The version number of the XP runtime.

[.lead]
Example

[source,typescript]
----
import {getVersion} from '/lib/xp/admin';

const version = getVersion();
----

=== getToolUrl

Returns the URL for an admin tool of a specific application.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Description
| application | string | Full application name (f.ex, `com.enonic.app.main`).
| tool | string | Name of the tool inside an app (f.ex, `main`).
|===

[.lead]
Returns

*string* : URL of the requested admin tool.

[.lead]
Example

[source,typescript]
----
import {getToolUrl} from '/lib/xp/admin';

const url = getToolUrl('com.enonic.app.main', 'main');
----

=== getHomeToolUrl

Returns the URL for the Home admin tool.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Description
| params | object | Parameter object. Optional.

[%header,cols="1%,1%,1%,1%,96%a"]
[frame="topbot"]
[grid="none"]
[caption=""]
.Properties
!===
! Name ! Type   ! Attributes ! Default ! Description
! type ! string ! <optional> ! server  ! URL type. Either `server` (server-relative URL) or `absolute`.
!===

|===

[.lead]
Returns

*string* : The URL pointing to the Home admin tool.

[.lead]
Example

[source,typescript]
----
import {getHomeToolUrl} from '/lib/xp/admin';

const url = getHomeToolUrl({type: 'absolute'});
----

=== extensionUrl

Returns the URL for an admin extension.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Description
| params | object | Parameter object.

[%header,cols="1%,1%,1%,1%,96%a"]
[frame="topbot"]
[grid="none"]
[caption=""]
.Properties
!===
! Name        ! Type   ! Attributes ! Default ! Description
! application ! string !            !         ! Application key that provides the extension.
! extension   ! string !            !         ! Name of the extension.
! type        ! string ! <optional> ! server  ! URL type. Either `server` (server-relative URL) or `absolute`.
! params      ! object ! <optional> !         ! Custom query parameters to append to the URL.
!===

|===

[.lead]
Returns

*string* : URL of the requested extension.

[.lead]
Example

[source,typescript]
----
import {extensionUrl} from '/lib/xp/admin';

const url = extensionUrl({
    application: 'com.enonic.app.main',
    extension: 'launcher',
    type: 'absolute',
    params: {
        id: '42'
    }
});
----

=== widgetUrl

WARNING: Deprecated — use <<extensionurl, `extensionUrl`>> instead. This function will be removed in future versions.

Returns the URL for a widget. Equivalent to calling `extensionUrl` with `extension` set to the widget name.

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name | Type | Description
| params | object | Parameter object.

[%header,cols="1%,1%,1%,1%,96%a"]
[frame="topbot"]
[grid="none"]
[caption=""]
.Properties
!===
! Name        ! Type   ! Attributes ! Default ! Description
! application ! string !            !         ! Application key that provides the widget.
! widget      ! string !            !         ! Name of the widget.
! type        ! string ! <optional> ! server  ! URL type. Either `server` (server-relative URL) or `absolute`.
! params      ! object ! <optional> !         ! Custom query parameters to append to the URL.
!===

|===

[.lead]
Returns

*string* : URL of the requested widget.
