= Components
:toc: right
:imagesdir: images

How to implement page, part, and layout components rendered by the site engine.

NOTE: Component implementations are only invoked by the <<../runtime/engines/site-engine#, Site Engine>>.

== Introduction

TIP: For a hands-on introduction to rendering pages with the Enonic framework, visit the https://developer.enonic.com/docs/my-first-site[My first site tutorial].

A component implementation is paired 1:1 with its <<../cms/pages#, page component descriptor>> and lives at a conventional location in the project. It exports the same HTTP functions as any other endpoint, but always runs in the context of a content item and may use <<contributions#, page contributions>>.

IMPORTANT: Markup returned by a component must have a single root element.


== Context

Component rendering is initiated by the <<../runtime/engines/site-engine#, Site Engine>>. The implementation is resolved when a client requests a specific page:

`HTTP request` -> `/site/<project>/<branch>/path/to/content` -> `resolve component` -> `invoke implementation`.

A content item is always available in your context.

API functions such as <<../libraries/lib-portal#getContent, portalLib.getContent()>> and <<../libraries/lib-portal#getComponent, portalLib.getComponent()>> automatically return values based on that context.

TIP: Thanks to the site engine's built-in access control, the current user is also guaranteed to have read permissions to the contextual content item.

== Pages

The page implementation lives next to its <<../cms/pages#, descriptor>> at `src/main/resources/cms/pages/<page-name>/<page-name>.ts`.

.Sample page implementation using the context
[source,typescript]
----
const portal = require('/lib/xp/portal');

exports.GET = (req) => {
  const content = portal.getContent();
  return {
    body: `<html>
            <body>
              <h1>${content.displayName}</h1>
            </body>
          </html>`
  };
};
----

== Parts

The part implementation lives next to its <<../cms/pages/parts#, descriptor>> at `src/main/resources/cms/parts/<part-name>/<part-name>.ts`.

.Sample part implementation using the form value
[source,typescript]
----
const portal = require('/lib/xp/portal');

exports.GET = (req) => {
  const config = portal.getComponent();
  return {
    body: `<div>
              <h1>${config.heading}</h1>
          </div>`
  };
};
----

== Layouts

The layout implementation lives next to its <<../cms/pages/layouts#, descriptor>> at `src/main/resources/cms/layouts/<layout-name>/<layout-name>.ts`.

.Sample layout using Thymeleaf to render two regions
[source,typescript]
----
const portal = require('/lib/xp/portal');
const thymeleaf = require('/lib/thymeleaf');

exports.GET = (req) => {
    const component = portal.getComponent();

    return {
        body: thymeleaf.render(resolve('./layout-two-column.html'), {
            leftRegion: component.regions["left"],
            rightRegion: component.regions["right"],
        })
    };
};
----

.Thymeleaf view to render layout
[source,html]
----
<div class="row">
  <div data-portal-region="left">
    <div data-th-each="component : ${leftRegion.components}" data-th-remove="tag">
      <div data-portal-component="${component.path}" data-th-remove="tag" />
    </div>
  </div>

  <div data-portal-region="right">
    <div data-th-each="component : ${rightRegion.components}" data-th-remove="tag">
      <div data-portal-component="${component.path}" data-th-remove="tag" />
    </div>
  </div>
</div>
----

== Regions

Component hierarchies are created via <<../cms/pages/regions#, regions>>. Rendering a region essentially boils down to rendering the components of that region.

To render a component, leave a component placeholder in the page or layout's response markup. Placeholders are then identified and rendered by the <<../runtime/engines/site-engine#, component rendering>> step of the site engine.

Components may contain new regions with new placeholders, so the process repeats until no placeholders remain in the response.

=== Component placeholders

Placeholders are formatted as HTML comments and include the component path. For example:

`<!--# COMPONENT /main/0/left/1 -\->`

For `text/html` responses, the site engine looks for component placeholders. For each placeholder, the component's implementation is invoked and the output merged into the response.


=== JavaScript example

A basic approach to rendering the main region of a page might look like this:

.Manually create component placeholders
[source,typescript]
----
const portal = require('/lib/xp/portal');

exports.GET = (req) => {
  // Get components of the main region
  const content = portal.getContent();
  const components = content.page.regions["main"].components || [];

  // Render with placeholders
  return {
    body: `<html><head>Placeholder demo</head>
            <body>
              <main data-portal-region="main">
                ${components.map((c) => `<!--# COMPONENT ${c.path} -->`).join('\n')}
              </main>
            </body>
          </html>`
  };
};
----

=== Templating example

Using Thymeleaf templating, placeholder generation might look like this:

.Page implementation passing region to template
[source,typescript]
----
const portal = require('/lib/xp/portal');
const thymeleaf = require('/lib/thymeleaf');

exports.GET = (req) => {
  // Get the contextual content item
  const content = portal.getContent();
  const mainRegion = content.page.regions["main"];

  // Render and return the result
  return {
    body: thymeleaf.render(view, mainRegion)
  };
};
----

.Thymeleaf template creating placeholders
[source,html]
----
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1>Page with placeholders</h1>
    <main data-portal-region="main">
      <div data-th-each="component : ${mainRegion.components}" data-th-remove="tag">
        <div data-portal-component="${component.path}" data-th-remove="tag" />
      </div>
    </main>
  </body>
</html>
----

== Fragments

Fragments are rendered via their existing implementations. However, since a fragment is just a subset of a page, it will likely render without any styling, header, or footer.

To mitigate this, add a <<mappings#, site mapping>> for the `portal:fragment` content type. The mapped implementation then runs every time a fragment is rendered.

.cms/site.yaml
[source,yaml]
----
kind: "Site"
mappings:
- controller: "/cms/pages/default/default.ts"
  match: "type:'portal:fragment'"
----

NOTE: Reusing your page implementation is often convenient, since it already does the job.

In the markup produced by the implementation, leave a placeholder for the fragment:

`<!--# COMPONENT / -\->`

The site engine then renders the fragment's components there.

Using Thymeleaf, the placeholder may be generated with the following line:

[source,html]
----
<div data-portal-component="fragment" data-th-remove="tag"/>
----


== Text components

Unlike other component types, <<../cms/pages/text#, Text components>> are built-in to XP and include a standard implementation.

NOTE: Bypass the built-in implementation by running your own code instead of placing a text component placeholder.
