= Component API
:toc: right
:imagesdir: images

The component API enables rendering of contextual page components directly `+:8080/site/<repo>/<branch>/<path-to-page>/_/component/<component-path>+`

== Component rendering pipeline

Page components may also be directly accessed.
For instance, one may render only the first part within in a page's main region.

The url pattern for direct rendering is: `+:8080/site/<repo>/<branch>/<path-to-page>/_/component/<region>/#+`. i.e. `+:8080/site/default/master/mysite/_/component/main/0+`.

Component rendering::  In this mode, only the *component rendering* step (as described above) will be executed.

[NOTE]
====
By exporting `POST` or any other HTTP method from the component implementation, it may also serve as the backend for the component.

Developers may also check if a component is rendered inline, or directly by using the request context. This may for instance be used to produce JSON in direct rendering mode rather than HTML, which is mandatory for inline mode.
====
