= Building Webapps
:toc: right
:imagesdir: webapps/images

The Webapp engine is responsible for processing of requests on the endpoint `<server>:<port>/webapp/<app-name>/*`


== Introduction

Enonic is capable of delivering web applications natively, without the need for a 3rd party front-end framework. The webapp engine provides a powerful and flexible platform for building and delivering web applications of all kinds, from simple static sites to complex, dynamic applications with advanced features like server-side rendering, real-time updates, and much more.


TODO: Tutorials here!


== Usage

To turn your application into a webapp, simply place an HTTP controller called `+/src/main/resources/webapp/webapp.js+` into your project.

When the application is deployed, the controller will be accessible from

`+<server>:<port>/webapp/<app-name>/+` (i.e. "localhost:8080/webapp/my.webapp/").

`+webapp.js+` now acts as an <<../../framework/http#http-controller,HTTP controller>> and may expose a function for each HTTP method that should be handled: i.e.
GET, POST, etc.

Below is an example webapp controller.

[source,JavaScript]
----
var mustache = require('/lib/xp/mustache');

// Handles a GET request
exports.GET = function (req) {

    var view = resolve('my-page.html');
    var params = {
        appId: app.name,
        title: 'Hello world'
    };

    return {
        body: mustache.render(view, params),
        contentType: 'text/html'
    };
};

// Handles a POST request
exports.POST = function (req) {
    var name = request.params.name;

    return {
        body: {'Hello': name},
        contentType: 'application/json'
    };
};

// Handles all other method requests
exports.all = function (req) {
    if (req.method === 'DELETE') {
        handleDelete(req);

    } else if (req.method === 'PUT') {
        handlePut(req);
    }

    return {
        body: {'Hello': name, 'Method': req.method},
        contentType: 'application/json'
    };
};
----

NOTE: To handle routing and filters in web apps, the implementer should use the https://market.enonic.com/vendors/enonic/router-lib[router library].


== Static webapps

Static webapps are pre-compiled web applications that serve static content, such as HTML, CSS, and JavaScript files. These web applications do not require any server-side processing. 

